deploy:
  variables:
    GIT_STRATEGY: none
    GIT_CHECKOUT: "false"
  stage: deploy
  script:
    - cd /home/sesota/etc-universe-frontend/
    - git pull
    # - npm install
    - ng build --prod
  tags: [test]
